// import Plotly from "plotly.js-dist";
// export default Plotly as typeof import("plotly.js");

// TODO: optimize bundle size
window.global = window;
var Plotly = require("plotly.js/lib/core") as typeof import("plotly.js");
Plotly.register([
  // traces
  require("plotly.js/lib/bar"),
  require("plotly.js/lib/box"),
  require("plotly.js/lib/heatmap"),
  require("plotly.js/lib/histogram"),
  require("plotly.js/lib/histogram2d"),
  require("plotly.js/lib/histogram2dcontour"),
  require("plotly.js/lib/contour"),

  require("plotly.js/lib/scatterternary"),
  require("plotly.js/lib/violin"),
  require("plotly.js/lib/funnel"),
  require("plotly.js/lib/waterfall"),
  // require("plotly.js/lib/image"), // NOGO
  require("plotly.js/lib/pie"),
  require("plotly.js/lib/sunburst"),
  require("plotly.js/lib/treemap"),
  require("plotly.js/lib/icicle"),
  require("plotly.js/lib/funnelarea"),

  require("plotly.js/lib/scatter3d"),
  require("plotly.js/lib/surface"),
  require("plotly.js/lib/isosurface"),
  require("plotly.js/lib/volume"),
  require("plotly.js/lib/mesh3d"),
  require("plotly.js/lib/cone"),
  require("plotly.js/lib/streamtube"),
  require("plotly.js/lib/scattergeo"),
  require("plotly.js/lib/choropleth"),
  require("plotly.js/lib/pointcloud"),
  require("plotly.js/lib/heatmapgl"),
  require("plotly.js/lib/parcats"),
  // require("plotly.js/lib/scattermapbox"),
  // require("plotly.js/lib/choroplethmapbox"),
  // // require("plotly.js/lib/densitymapbox"),
  require("plotly.js/lib/sankey"),
  require("plotly.js/lib/indicator"),
  require("plotly.js/lib/table"),
  require("plotly.js/lib/carpet"),
  require("plotly.js/lib/scattercarpet"),
  require("plotly.js/lib/contourcarpet"),
  require("plotly.js/lib/ohlc"),
  require("plotly.js/lib/candlestick"),
  require("plotly.js/lib/scatterpolar"),
  require("plotly.js/lib/barpolar"),

  // transforms
  require("plotly.js/lib/aggregate"),
  require("plotly.js/lib/filter"),
  require("plotly.js/lib/groupby"),
  require("plotly.js/lib/sort"),

  // components
  require("plotly.js/lib/calendars"),

  // locales
  require("plotly.js/lib/locales/af.js"),
  require("plotly.js/lib/locales/am.js"),
  require("plotly.js/lib/locales/ar-dz.js"),
  require("plotly.js/lib/locales/ar-eg.js"),
  require("plotly.js/lib/locales/ar.js"),
  require("plotly.js/lib/locales/az.js"),
  require("plotly.js/lib/locales/bg.js"),
  require("plotly.js/lib/locales/bs.js"),
  require("plotly.js/lib/locales/ca.js"),
  require("plotly.js/lib/locales/cs.js"),
  require("plotly.js/lib/locales/cy.js"),
  require("plotly.js/lib/locales/da.js"),
  require("plotly.js/lib/locales/de-ch.js"),
  require("plotly.js/lib/locales/de.js"),
  require("plotly.js/lib/locales/el.js"),
  require("plotly.js/lib/locales/eo.js"),
  require("plotly.js/lib/locales/es-ar.js"),
  require("plotly.js/lib/locales/es-pe.js"),
  require("plotly.js/lib/locales/es.js"),
  require("plotly.js/lib/locales/et.js"),
  require("plotly.js/lib/locales/eu.js"),
  require("plotly.js/lib/locales/fa.js"),
  require("plotly.js/lib/locales/fi.js"),
  require("plotly.js/lib/locales/fo.js"),
  require("plotly.js/lib/locales/fr-ch.js"),
  require("plotly.js/lib/locales/fr.js"),
  require("plotly.js/lib/locales/gl.js"),
  require("plotly.js/lib/locales/gu.js"),
  require("plotly.js/lib/locales/he.js"),
  require("plotly.js/lib/locales/hi-in.js"),
  require("plotly.js/lib/locales/hr.js"),
  require("plotly.js/lib/locales/hu.js"),
  require("plotly.js/lib/locales/hy.js"),
  require("plotly.js/lib/locales/id.js"),
  require("plotly.js/lib/locales/is.js"),
  require("plotly.js/lib/locales/it.js"),
  require("plotly.js/lib/locales/ja.js"),
  require("plotly.js/lib/locales/ka.js"),
  require("plotly.js/lib/locales/km.js"),
  require("plotly.js/lib/locales/ko.js"),
  require("plotly.js/lib/locales/lt.js"),
  require("plotly.js/lib/locales/lv.js"),
  require("plotly.js/lib/locales/me-me.js"),
  require("plotly.js/lib/locales/me.js"),
  require("plotly.js/lib/locales/mk.js"),
  require("plotly.js/lib/locales/ml.js"),
  require("plotly.js/lib/locales/ms.js"),
  require("plotly.js/lib/locales/mt.js"),
  require("plotly.js/lib/locales/nl-be.js"),
  require("plotly.js/lib/locales/nl.js"),
  require("plotly.js/lib/locales/no.js"),
  require("plotly.js/lib/locales/pa.js"),
  require("plotly.js/lib/locales/pl.js"),
  require("plotly.js/lib/locales/pt-br.js"),
  require("plotly.js/lib/locales/pt-pt.js"),
  require("plotly.js/lib/locales/rm.js"),
  require("plotly.js/lib/locales/ro.js"),
  require("plotly.js/lib/locales/ru.js"),
  require("plotly.js/lib/locales/si.js"),
  require("plotly.js/lib/locales/sk.js"),
  require("plotly.js/lib/locales/sl.js"),
  require("plotly.js/lib/locales/sq.js"),
  require("plotly.js/lib/locales/sr-sr.js"),
  require("plotly.js/lib/locales/sr.js"),
  require("plotly.js/lib/locales/sv.js"),
  require("plotly.js/lib/locales/sw.js"),
  require("plotly.js/lib/locales/ta.js"),
  require("plotly.js/lib/locales/th.js"),
  require("plotly.js/lib/locales/tr.js"),
  require("plotly.js/lib/locales/tt.js"),
  require("plotly.js/lib/locales/uk.js"),
  require("plotly.js/lib/locales/ur.js"),
  require("plotly.js/lib/locales/vi.js"),
  require("plotly.js/lib/locales/zh-cn.js"),
  require("plotly.js/lib/locales/zh-hk.js"),
  require("plotly.js/lib/locales/zh-tw.js"),
]);

export default Plotly;
//*/
