name: Build on release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: npm install

    - name: Update package.json
      run: npm version ${{ github.ref_name }} --git-tag-version false

    - name: Build
      run: npm run build

    - name: Upload release asset
      uses: svenstaro/upload-release-action@v2
      with:
        file: dist/plotly-graph-card.js
