name: HACS-Validate

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  hacs:
    name: HACS Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: HACS Action
        uses: hacs/action@main
        with:
          category: plugin
